dataset: 'cifar10'
num_classes: 10
backbone: 'resnet32_fe'

imb_factor: 0.1
feat_size: 64

batch_size: 128
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
epochs: 200

fit_threshold: 0.8
bank_size: 128
start_aug: 0


log_dir: 'logs/cifar10_lt_01'
num_workers: 4

ckps: './ckps/cifar10_lt_01'