dataset: 'cifar100'
num_classes: 100
backbone: 'resnet32_fe'

imb_factor: 0.02
feat_size: 64

batch_size: 128
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
epochs: 200

fit_threshold: 0.8
bank_size: 128
start_aug: 0


log_dir: 'logs/cifar100_lt_002'
num_workers: 4

ckps: './ckps/cifar100_lt_002'
cos: True